// Table de correspondance IP : nom de club deposé -> nom de VILLE uniquement.
// Le projet ne référence les clubs que par leur ville (pas de marque déposée,
// pas d'écusson, pas de maillot). Appliquée par les deux générateurs de data
// (FIFA et European Soccer Database) afin qu'aucun nom de club officiel
// n'apparaisse dans le jeu. Couvre aussi les variantes courtes de FIFA 23.
export const CITY = {
  // — formes "officielles" (datasets) —
  "AC Ajaccio": "Ajaccio",
  "GFC Ajaccio": "Ajaccio",
  "AC Arles-Avignon": "Arles",
  "AJ Auxerre": "Auxerre",
  "AS Monaco": "Monaco",
  "AS Nancy Lorraine": "Nancy",
  "AS Nancy-Lorraine": "Nancy",
  "AS Saint-Étienne": "Saint-Étienne",
  "Amiens SC": "Amiens",
  "Angers SCO": "Angers",
  "Clermont Foot 63": "Clermont",
  "Dijon FCO": "Dijon",
  "ES Troyes AC": "Troyes",
  "ESTAC Troyes": "Troyes",
  "En Avant de Guingamp": "Guingamp",
  "FC Girondins de Bordeaux": "Bordeaux",
  "FC Lorient": "Lorient",
  "FC Metz": "Metz",
  "FC Nantes": "Nantes",
  "FC Sochaux-Montbéliard": "Sochaux",
  "Grenoble Foot 38": "Grenoble",
  "LOSC Lille": "Lille",
  "Le Havre AC": "Le Havre",
  "Le Mans FC": "Le Mans",
  "Montpellier Hérault SC": "Montpellier",
  "Nîmes Olympique": "Nîmes",
  "OGC Nice": "Nice",
  "Olympique Lyonnais": "Lyon",
  "Olympique de Marseille": "Marseille",
  "Paris Saint-Germain": "Paris",
  "RC Lens": "Lens",
  "RC Strasbourg Alsace": "Strasbourg",
  "Racing Club de Lens": "Lens",
  "SC Bastia": "Bastia",
  "Stade Brestois 29": "Brest",
  "Stade Malherbe Caen": "Caen",
  "Stade Rennais FC": "Rennes",
  "Stade de Reims": "Reims",
  "Toulouse Football Club": "Toulouse",
  "US Boulogne Cote D'Opale": "Boulogne",
  "Valenciennes FC": "Valenciennes",
  "Évian Thonon Gaillard FC": "Évian",
  // — variantes courtes / anonymisées de FIFA 23 —
  "Paris Saint Germain": "Paris",
  "Olympique Marseille": "Marseille",
  Monaco: "Monaco",
  Nice: "Nice",
  Rennes: "Rennes",
  Strasbourg: "Strasbourg",
  Lille: "Lille",
  Nantes: "Nantes",
  Montpellier: "Montpellier",
  Lens: "Lens",
  Brest: "Brest",
  Reims: "Reims",
  Troyes: "Troyes",
  Auxerre: "Auxerre",
  Toulouse: "Toulouse",
  Lorient: "Lorient",
  Clermont: "Clermont",
  Ajaccio: "Ajaccio",
  Lyon: "Lyon",
  Marseille: "Marseille",
  Bordeaux: "Bordeaux",
  "Saint-Étienne": "Saint-Étienne",
  Metz: "Metz",
};

export const toCity = (name) => CITY[(name || "").trim()] ?? (name || "").trim();
